#include "ConditionCreator.h"
#include "Behaviours/Spawn1558533534825.h"
#include "Behaviours/Stop1555602210283.h"
#include "Behaviours/Test1559635479527.h"
#include "Behaviours/TestCodeGen1568112052043.h"
#include "ServeMaster1555601736192.h"

using namespace alicaAutogenerated;
namespace alica {

ConditionCreator::ConditionCreator() {}
ConditionCreator::~ConditionCreator() {}

std::shared_ptr<BasicCondition>
ConditionCreator::createConditions(long conditionConfId) {
  switch (conditionConfId) {
  case 1558533620473:
    return std::make_shared<PreCondition1558533620473>();
    break;
  case 1558533654035:
    return std::make_shared<PreCondition1558533654035>();
    break;
  case 1558533667052:
    return std::make_shared<PreCondition1558533667052>();
    break;
  case 1558533725689:
    return std::make_shared<PreCondition1558533725689>();
    break;
  case 1560934538125:
    return std::make_shared<PreCondition1560934538125>();
    break;
  case 1568105583307:
    return std::make_shared<PreCondition1568105583307>();
    break;
  case 1568119815697:
    return std::make_shared<RunTimeCondition1568119815697>();
    break;
  default:
    std::cerr << "ConditionCreator: Unknown condition id requested: "
              << conditionConfId << std::endl;
    throw new std::exception();
    break;
  }
}
} // namespace alica
