#include "Human1575291300084.h"
/*PROTECTED REGION ID(eph1575291300084) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:Human
/* generated comment
    Task: Human  -> EntryPoint-ID: 1575291327598
*/
shared_ptr<UtilityFunction> UtilityFunction1575291300084::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1575291300084) ENABLED START*/
    std::shared_ptr<UtilityFunction> defaultFunction = std::make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;
    /*PROTECTED REGION END*/
}
} // namespace alicaAutogenerated
