#include "Operate1575655614484.h"
/*PROTECTED REGION ID(eph1575655614484) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:Operate
/**
 * Task: 1555601344076  -> EntryPoint-ID: 1575655644510
 * Task: 1575291322015  -> EntryPoint-ID: 1575655650043
 */
shared_ptr<UtilityFunction> UtilityFunction1575655614484::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1575655614484) ENABLED START*/
    std::shared_ptr<UtilityFunction> defaultFunction = std::make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;
    /*PROTECTED REGION END*/
}
} // namespace alicaAutogenerated
