#include "ServeMaster1555601736192.h"
/*PROTECTED REGION ID(eph1555601736192) ENABLED START*/
#include <engine/IRoleAssignment.h>
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:ServeMaster
// Check of PreCondition - (Name): 1558533725689, (ConditionString): Stop received , (Comment) :

/*
 * Available Vars:
 */
bool PreCondition1558533725689::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1558533725689) ENABLED START*/
    // TODO implement wm and check whether stop/start message was received
    return false;
    /*PROTECTED REGION END*/
}
/* generated comment
    Task: Serve  -> EntryPoint-ID: 1555601746711
*/
shared_ptr<UtilityFunction> UtilityFunction1555601736192::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1555601736192) ENABLED START*/
    std::shared_ptr<UtilityFunction> defaultFunction = std::make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1558533620473, ConditionString: Start received!, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): Stop, (PlanID): 1555602210283
 *
 * Tasks:
 *
 *   - Serve (1555601344076) (Entrypoint: 1555601746711)
 *
 * States:
 *
 *   - Stop (1555601748848)
 *   - Spawn (1558533460297)
 *   - Serve (1558533461982)
 *   - SimHuman (1575291091434)
 *
 * Vars:
 */
bool PreCondition1558533620473::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1558533492085) ENABLED START*/
    auto lastCmd = this->wm->rawSensorData.getAgentCmdBuffer().getLastValidContent();
    return lastCmd.has_value() && lastCmd->cmd == control::AgentCommand::START;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1558533654035, ConditionString: Stop received, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): Spawn, (PlanID): 1558533534825
 *
 * Tasks:
 *
 *   - Serve (1555601344076) (Entrypoint: 1555601746711)
 *
 * States:
 *
 *   - Stop (1555601748848)
 *   - Spawn (1558533460297)
 *   - Serve (1558533461982)
 *   - SimHuman (1575291091434)
 *
 * Vars:
 */
bool PreCondition1558533654035::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1558533494595) ENABLED START*/
    auto lastCmd = this->wm->rawSensorData.getAgentCmdBuffer().getLastValidContent();
    return lastCmd.has_value() && lastCmd->cmd == control::AgentCommand::STOP;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1558533667052, ConditionString: Spawn successful (acknowledge through received sim sensor values) && I am a robot, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): Spawn, (PlanID): 1558533534825
 *
 * Tasks:
 *
 *   - Serve (1555601344076) (Entrypoint: 1555601746711)
 *
 * States:
 *
 *   - Stop (1555601748848)
 *   - Spawn (1558533460297)
 *   - Serve (1558533461982)
 *   - SimHuman (1575291091434)
 *
 * Vars:
 */
bool PreCondition1558533667052::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1558533514929) ENABLED START*/
    const alica::Role* ownRole = this->wm->getEngine()->getRoleAssignment()->getRole(this->wm->getOwnId());
    return this->wm->sRGSimData.isLocalised() && ownRole->getName().compare("Assistant") == 0;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1575291183488, ConditionString: Spawn successful (acknowledge through received sim sensor values) && I am a simulated human, Comment :
 * MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): Spawn, (PlanID): 1558533534825
 *
 * Tasks:
 *
 *   - Serve (1555601344076) (Entrypoint: 1555601746711)
 *
 * States:
 *
 *   - Stop (1555601748848)
 *   - Spawn (1558533460297)
 *   - Serve (1558533461982)
 *   - SimHuman (1575291091434)
 *
 * Vars:
 */
bool PreCondition1575291183488::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1575291118178) ENABLED START*/
    const alica::Role* ownRole = this->wm->getEngine()->getRoleAssignment()->getRole(this->wm->getOwnId());
    return this->wm->sRGSimData.isLocalised() && ownRole->getName().compare("Human") == 0;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1560934538125, ConditionString: Stop received!, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): Serve, (PlanID): 1568825275605
 *
 * Tasks:
 *
 *   - Serve (1555601344076) (Entrypoint: 1555601746711)
 *
 * States:
 *
 *   - Stop (1555601748848)
 *   - Spawn (1558533460297)
 *   - Serve (1558533461982)
 *   - SimHuman (1575291091434)
 *
 * Vars:
 */
bool PreCondition1560934538125::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1558533714287) ENABLED START*/
    auto lastCmd = this->wm->rawSensorData.getAgentCmdBuffer().getLastValidContent();
    return lastCmd.has_value() && lastCmd->cmd == control::AgentCommand::STOP;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1575291206583, ConditionString: Stop received!, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): Human, (PlanID): 1575294066871
 *
 * Tasks:
 *
 *   - Serve (1555601344076) (Entrypoint: 1555601746711)
 *
 * States:
 *
 *   - Stop (1555601748848)
 *   - Spawn (1558533460297)
 *   - Serve (1558533461982)
 *   - SimHuman (1575291091434)
 *
 * Vars:
 */
bool PreCondition1575291206583::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1575291123141) ENABLED START*/
    auto lastCmd = this->wm->rawSensorData.getAgentCmdBuffer().getLastValidContent();
    return lastCmd.has_value() && lastCmd->cmd == control::AgentCommand::STOP;
    /*PROTECTED REGION END*/
}
} // namespace alicaAutogenerated
