#include "Transport1573418869596.h"
/*PROTECTED REGION ID(eph1573418869596) ENABLED START*/
#include <srg/World.h>
#include <srg/tasks/CommandHandler.h>
#include <srg/tasks/Task.h>
#include <srg/world/Cell.h>
#include <srg/world/Object.h>
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:Transport
/**
 * Task: Fetch  -> EntryPoint-ID: 1573418933317
 */
shared_ptr<UtilityFunction> UtilityFunction1573418869596::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1573418869596) ENABLED START*/
    std::shared_ptr<UtilityFunction> defaultFunction = std::make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;
    /*PROTECTED REGION END*/
}
/**
 * Outgoing transition:
 *   - Name: 1573419765536, ConditionString: Object found, now move to it!, Comment: MISSING_COMMENT
 *
 * Abstractplans in current state:
 *   - Search (1573419059418)
 *
 * Tasks in plan:
 *   - Fetch (1555601323994) (Entrypoint: 1573418933317)
 *
 * States in plan:
 *   - Search (1573418936395)
 *   - PickUp (1573418937725)
 *   - MoveDestination (1573418938883)
 *   - PutDown (1573418939737)
 *   - MoveClose (1573418941076)
 *   - TransportDone (1573418943460)
 *
 * Variables of plan:
 */
bool PreCondition1573419765536::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1573419007368) ENABLED START*/
    auto taskSequence = this->wm->dialogueManager.commandHandler->getActiveTaskSequence();
    if (!taskSequence) {
        return true;
    }
    auto activeTask = taskSequence->getActiveTask();
    return rp->isAnyChildStatus(PlanStatus::Success) && activeTask && activeTask->type == srg::tasks::TaskType::Move;
    /*PROTECTED REGION END*/
}
/**
 * Outgoing transition:
 *   - Name: 1573419810456, ConditionString: Object picked up, now bring it somewhere!, Comment: MISSING_COMMENT
 *
 * Abstractplans in current state:
 *   - Manipulate (1571687572903)
 *
 * Tasks in plan:
 *   - Fetch (1555601323994) (Entrypoint: 1573418933317)
 *
 * States in plan:
 *   - Search (1573418936395)
 *   - PickUp (1573418937725)
 *   - MoveDestination (1573418938883)
 *   - PutDown (1573418939737)
 *   - MoveClose (1573418941076)
 *   - TransportDone (1573418943460)
 *
 * Variables of plan:
 */
bool PreCondition1573419810456::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1573418998111) ENABLED START*/
    auto taskSequence = this->wm->dialogueManager.commandHandler->getActiveTaskSequence();
    if (!taskSequence) {
        return true;
    }
    auto activeTask = taskSequence->getActiveTask();
    return rp->isAnyChildStatus(PlanStatus::Success) && activeTask && activeTask->type == srg::tasks::TaskType::Move;
    /*PROTECTED REGION END*/
}
/**
 * Outgoing transition:
 *   - Name: 1582991345020, ConditionString: PickUp is not executable, because its object vanished. Go back to Search!, Comment: MISSING_COMMENT
 *
 * Abstractplans in current state:
 *   - Manipulate (1571687572903)
 *
 * Tasks in plan:
 *   - Fetch (1555601323994) (Entrypoint: 1573418933317)
 *
 * States in plan:
 *   - Search (1573418936395)
 *   - PickUp (1573418937725)
 *   - MoveDestination (1573418938883)
 *   - PutDown (1573418939737)
 *   - MoveClose (1573418941076)
 *   - TransportDone (1573418943460)
 *
 * Variables of plan:
 */
bool PreCondition1582991345020::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1582991345018) ENABLED START*/
    auto taskSequence = this->wm->dialogueManager.commandHandler->getActiveTaskSequence();
    if (!taskSequence) {
        return true;
    }
    auto activeTask = taskSequence->getActiveTask();
    return activeTask && activeTask->type == srg::tasks::TaskType::Search;
    /*PROTECTED REGION END*/
}
/**
 * Outgoing transition:
 *   - Name: 1573419828606, ConditionString: Object carried to destination, now put it down., Comment: MISSING_COMMENT
 *
 * Abstractplans in current state:
 *   - Move (1568825137528)
 *
 * Tasks in plan:
 *   - Fetch (1555601323994) (Entrypoint: 1573418933317)
 *
 * States in plan:
 *   - Search (1573418936395)
 *   - PickUp (1573418937725)
 *   - MoveDestination (1573418938883)
 *   - PutDown (1573418939737)
 *   - MoveClose (1573418941076)
 *   - TransportDone (1573418943460)
 *
 * Variables of plan:
 */
bool PreCondition1573419828606::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1573419000441) ENABLED START*/

    auto taskSequence = this->wm->dialogueManager.commandHandler->getActiveTaskSequence();
    if (!taskSequence) {
        return true;
    }
    auto activeTask = taskSequence->getActiveTask();
    return rp->isAnyChildStatus(PlanStatus::Success) && activeTask && activeTask->type == srg::tasks::TaskType::PutDown;
    /*PROTECTED REGION END*/
}
/**
 * Outgoing transition:
 *   - Name: 1573419841944, ConditionString: Object put down, transport task successful!, Comment: MISSING_COMMENT
 *
 * Abstractplans in current state:
 *   - Manipulate (1571687572903)
 *
 * Tasks in plan:
 *   - Fetch (1555601323994) (Entrypoint: 1573418933317)
 *
 * States in plan:
 *   - Search (1573418936395)
 *   - PickUp (1573418937725)
 *   - MoveDestination (1573418938883)
 *   - PutDown (1573418939737)
 *   - MoveClose (1573418941076)
 *   - TransportDone (1573418943460)
 *
 * Variables of plan:
 */
bool PreCondition1573419841944::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1573419003625) ENABLED START*/
    return rp->isAnyChildStatus(PlanStatus::Success);
    /*PROTECTED REGION END*/
}
/**
 * Outgoing transition:
 *   - Name: 1573419800282, ConditionString: At the object, now pick it up!, Comment: MISSING_COMMENT
 *
 * Abstractplans in current state:
 *   - Move (1568825137528)
 *
 * Tasks in plan:
 *   - Fetch (1555601323994) (Entrypoint: 1573418933317)
 *
 * States in plan:
 *   - Search (1573418936395)
 *   - PickUp (1573418937725)
 *   - MoveDestination (1573418938883)
 *   - PutDown (1573418939737)
 *   - MoveClose (1573418941076)
 *   - TransportDone (1573418943460)
 *
 * Variables of plan:
 */
bool PreCondition1573419800282::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1573419009128) ENABLED START*/
    auto taskSequence = this->wm->dialogueManager.commandHandler->getActiveTaskSequence();
    if (!taskSequence) {
        return true;
    }
    auto activeTask = taskSequence->getActiveTask();
    return rp->isAnyChildStatus(PlanStatus::Success) && activeTask && activeTask->type == srg::tasks::TaskType::PickUp;
    /*PROTECTED REGION END*/
}
/**
 * Outgoing transition:
 *   - Name: 1582991323350, ConditionString: MoveClose does not work anymore, because its target object vanished! Go back to Search., Comment: MISSING_COMMENT
 *
 * Abstractplans in current state:
 *   - Move (1568825137528)
 *
 * Tasks in plan:
 *   - Fetch (1555601323994) (Entrypoint: 1573418933317)
 *
 * States in plan:
 *   - Search (1573418936395)
 *   - PickUp (1573418937725)
 *   - MoveDestination (1573418938883)
 *   - PutDown (1573418939737)
 *   - MoveClose (1573418941076)
 *   - TransportDone (1573418943460)
 *
 * Variables of plan:
 */
bool PreCondition1582991323350::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1582991323347) ENABLED START*/
    auto taskSequence = this->wm->dialogueManager.commandHandler->getActiveTaskSequence();
    if (!taskSequence) {
        return true;
    }
    auto activeTask = taskSequence->getActiveTask();
    return activeTask && activeTask->type == srg::tasks::TaskType::Search;
    /*PROTECTED REGION END*/
}
} // namespace alicaAutogenerated
