#include "Transport1573418869596.h"
/*PROTECTED REGION ID(eph1573418869596) ENABLED START*/
#include <srg/tasks/TaskHandler.h>
#include <srg/tasks/Task.h>
#include <srg/world/Cell.h>
#include <srg/world/Object.h>
#include <srg/World.h>
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:Transport
/* generated comment
    Task: 1555601323994  -> EntryPoint-ID: 1573418933317
*/
shared_ptr<UtilityFunction> UtilityFunction1573418869596::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1573418869596) ENABLED START*/
    std::shared_ptr<UtilityFunction> defaultFunction = std::make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1573419746851, ConditionString: Found & Close By, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): 1573419059418, (PlanID): 1573419059418
 *
 * Tasks:
 *
 *   - 1555601323994 (1555601323994) (Entrypoint: 1573418933317)
 *
 * States:
 *
 *   - Search (1573418936395)
 *   - PickUp (1573418937725)
 *   - Move (1573418938883)
 *   - PutDown (1573418939737)
 *   - MoveClose (1573418941076)
 *   - TransportDone (1573418943460)
 *
 * Vars:
 */
bool PreCondition1573419746851::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1573418996008) ENABLED START*/
    if (!rp->isAnyChildStatus(PlanStatus::Success)) {
        return false;
    }
    auto activeCommand = this->wm->dialogueManager.taskHandler->getActiveTask();
    if (activeCommand->getInformation()->type != srg::tasks::TaskType::Search) {
        return false;
    }
    srg::tasks::Task* transportTask = static_cast<srg::tasks::Task*>(activeCommand->getInformation());
    return false; //transportTask->foundObject(this->wm) && transportTask->closeToObject(this->wm);
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1573419765536, ConditionString: Found & Too far away for grasping, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): 1573419059418, (PlanID): 1573419059418
 *
 * Tasks:
 *
 *   - 1555601323994 (1555601323994) (Entrypoint: 1573418933317)
 *
 * States:
 *
 *   - Search (1573418936395)
 *   - PickUp (1573418937725)
 *   - Move (1573418938883)
 *   - PutDown (1573418939737)
 *   - MoveClose (1573418941076)
 *   - TransportDone (1573418943460)
 *
 * Vars:
 */
bool PreCondition1573419765536::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1573419007368) ENABLED START*/
    if (!rp->isAnyChildStatus(PlanStatus::Success)) {
        return false;
    }
    auto activeCommand = this->wm->dialogueManager.taskHandler->getActiveTask();
    if (activeCommand->getInformation()->type != srg::tasks::TaskType::Search) {
        return false;
    }
    srg::tasks::Task* transportTask = static_cast<srg::tasks::Task*>(activeCommand->getInformation());
    return false; //transportTask->foundObject(this->wm) && !transportTask->closeToObject(wm);
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1573419810456, ConditionString: Picked up, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): 1571687572903, (PlanID): 1571687572903
 *
 * Tasks:
 *
 *   - 1555601323994 (1555601323994) (Entrypoint: 1573418933317)
 *
 * States:
 *
 *   - Search (1573418936395)
 *   - PickUp (1573418937725)
 *   - Move (1573418938883)
 *   - PutDown (1573418939737)
 *   - MoveClose (1573418941076)
 *   - TransportDone (1573418943460)
 *
 * Vars:
 */
bool PreCondition1573419810456::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1573418998111) ENABLED START*/
    if (!rp->isAnyChildStatus(PlanStatus::Success)) {
        return false;
    }
    auto activeCommand = this->wm->dialogueManager.taskHandler->getActiveTask();
    if (activeCommand->getInformation()->type != srg::tasks::TaskType::Search) {
        return false;
    }
    srg::tasks::Task* transportTask = static_cast<srg::tasks::Task*>(activeCommand->getInformation());
    return false; //transportTask->pickedObject(this->wm);
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1573419828606, ConditionString: Moved to destination, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): 1568825137528, (PlanID): 1568825137528
 *
 * Tasks:
 *
 *   - 1555601323994 (1555601323994) (Entrypoint: 1573418933317)
 *
 * States:
 *
 *   - Search (1573418936395)
 *   - PickUp (1573418937725)
 *   - Move (1573418938883)
 *   - PutDown (1573418939737)
 *   - MoveClose (1573418941076)
 *   - TransportDone (1573418943460)
 *
 * Vars:
 */
bool PreCondition1573419828606::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1573419000441) ENABLED START*/
    if (!rp->isAnyChildStatus(PlanStatus::Success)) {
        return false;
    }
    auto activeCommand = this->wm->dialogueManager.taskHandler->getActiveTask();
    if (activeCommand->getInformation()->type != srg::tasks::TaskType::Search) {
        return false;
    }
    srg::tasks::Task* transportTask = static_cast<srg::tasks::Task*>(activeCommand->getInformation());
    return false; //transportTask->movedToDestination(this->wm);
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1573419841944, ConditionString: Object put down, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): 1571687572903, (PlanID): 1571687572903
 *
 * Tasks:
 *
 *   - 1555601323994 (1555601323994) (Entrypoint: 1573418933317)
 *
 * States:
 *
 *   - Search (1573418936395)
 *   - PickUp (1573418937725)
 *   - Move (1573418938883)
 *   - PutDown (1573418939737)
 *   - MoveClose (1573418941076)
 *   - TransportDone (1573418943460)
 *
 * Vars:
 */
bool PreCondition1573419841944::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1573419003625) ENABLED START*/
    if (!rp->isAnyChildStatus(PlanStatus::Success)) {
        return false;
    }
    auto activeCommand = this->wm->dialogueManager.taskHandler->getActiveTask();
    if (activeCommand->getInformation()->type != srg::tasks::TaskType::Search) {
        return false;
    }
    srg::tasks::Task* transportTask = static_cast<srg::tasks::Task*>(activeCommand->getInformation());
    return transportTask->checkSuccess(this->wm);
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1573419800282, ConditionString: Found & Close by, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): 1568825137528, (PlanID): 1568825137528
 *
 * Tasks:
 *
 *   - 1555601323994 (1555601323994) (Entrypoint: 1573418933317)
 *
 * States:
 *
 *   - Search (1573418936395)
 *   - PickUp (1573418937725)
 *   - Move (1573418938883)
 *   - PutDown (1573418939737)
 *   - MoveClose (1573418941076)
 *   - TransportDone (1573418943460)
 *
 * Vars:
 */
bool PreCondition1573419800282::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1573419009128) ENABLED START*/
    if (!rp->isAnyChildStatus(PlanStatus::Success)) {
        return false;
    }
    auto activeCommand = this->wm->dialogueManager.taskHandler->getActiveTask();
    if (activeCommand->getInformation()->type != srg::tasks::TaskType::Search) {
        return false;
    }
    srg::tasks::Task* transportTask = static_cast<srg::tasks::Task*>(activeCommand->getInformation());
    return false;// transportTask->foundObject(this->wm) && transportTask->closeToObject(this->wm);
    /*PROTECTED REGION END*/
}
} // namespace alicaAutogenerated
