#include "UtilityFunctionCreator.h"
#include "ServeMaster1555601736192.h"
#include "Serve1568825275605.h"
#include "Transport1573418869596.h"
#include <iostream>

using namespace alicaAutogenerated;

namespace alica
{

    UtilityFunctionCreator::~UtilityFunctionCreator()
    {
    }

    UtilityFunctionCreator::UtilityFunctionCreator()
    {
    }


    std::shared_ptr<BasicUtilityFunction> UtilityFunctionCreator::createUtility(long utilityfunctionConfId)
    {
        switch(utilityfunctionConfId)
        {
            case 1555601736192:
                return std::make_shared<UtilityFunction1555601736192>();
                break;
            case 1568825275605:
                return std::make_shared<UtilityFunction1568825275605>();
                break;
            case 1573418869596:
                return std::make_shared<UtilityFunction1573418869596>();
                break;
            default:
            std::cerr << "UtilityFunctionCreator: Unknown utility requested: " << utilityfunctionConfId << std::endl;
            throw new std::exception();
            break;
        }
    }


}
