#pragma once

#include <engine/BasicConstraint.h>
#include <memory>
#include <iostream>

using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

    class Constraint1558533725689 : public BasicConstraint
    {
        void getConstraint(std::shared_ptr<ProblemDescriptor> c, std::shared_ptr<RunningPlan> rp);
    };
} /* namespace alica */
