

#include "DomainCondition.h"
/*PROTECTED REGION ID(incBC1581966891046) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
/*PROTECTED REGION ID(meth1581966891046) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/

class PreCondition1581966891048 : public DomainCondition
{
    bool evaluate(std::shared_ptr<RunningPlan> rp);
};
class RunTimeCondition1581966891049 : public DomainCondition
{
    bool evaluate(std::shared_ptr<RunningPlan> rp);
};
class PostCondition1581966891050 : public DomainCondition
{
    bool evaluate(std::shared_ptr<RunningPlan> rp);
};
} // namespace alicaAutogenerated
