

#include "DomainCondition.h"
/*PROTECTED REGION ID(incBC1555602210283) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
/*PROTECTED REGION ID(meth1555602210283) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/

class PreCondition1568105583307 : public DomainCondition
{
    bool evaluate(std::shared_ptr<RunningPlan> rp);
};
class RunTimeCondition1568119815697 : public DomainCondition
{
    bool evaluate(std::shared_ptr<RunningPlan> rp);
};
} // namespace alicaAutogenerated
