// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: AgentCommandMsg.capnp

#include "AgentCommandMsg.capnp.h"

namespace capnp {
namespace schemas {
static const ::capnp::_::AlignedData<56> b_a1be158cb99fb677 = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
    119, 182, 159, 185, 140,  21, 190, 161,
     22,   0,   0,   0,   1,   0,   1,   0,
    238, 250, 245, 166,  77,  98, 218, 214,
      1,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0,  50,   1,   0,   0,
     37,   0,   0,   0,  39,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     57,   0,   0,   0, 119,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     65, 103, 101, 110, 116,  67, 111, 109,
    109,  97, 110, 100,  77, 115, 103,  46,
     99,  97, 112, 110, 112,  58,  65, 103,
    101, 110, 116,  67, 111, 109, 109,  97,
    110, 100,  77, 115, 103,   0,   0,   0,
      8,   0,   0,   0,   1,   0,   1,   0,
     30, 113,  63, 187, 239,  68,  22, 218,
      9,   0,   0,   0,  50,   0,   0,   0,
    130, 167, 201,  94, 136,  16,  20, 199,
      5,   0,   0,   0,  42,   0,   0,   0,
    115, 116,  97, 114, 116,   0,   0,   0,
    115, 116, 111, 112,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     41,   0,   0,   0,  90,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     40,   0,   0,   0,   3,   0,   1,   0,
     52,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     49,   0,   0,   0,  34,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     44,   0,   0,   0,   3,   0,   1,   0,
     56,   0,   0,   0,   2,   0,   1,   0,
    114, 101,  99, 101, 105, 118, 101, 114,
     73, 100,   0,   0,   0,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
    171,  96, 200,  45, 119,  27,  93, 219,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     99, 109, 100,   0,   0,   0,   0,   0,
      6,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      6,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_a1be158cb99fb677 = b_a1be158cb99fb677.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_a1be158cb99fb677[] = {
  &s_db5d1b772dc860ab,
};
static const uint16_t m_a1be158cb99fb677[] = {1, 0};
static const uint16_t i_a1be158cb99fb677[] = {0, 1};
const ::capnp::_::RawSchema s_a1be158cb99fb677 = {
  0xa1be158cb99fb677, b_a1be158cb99fb677.words, 56, d_a1be158cb99fb677, m_a1be158cb99fb677,
  1, 2, i_a1be158cb99fb677, nullptr, nullptr, { &s_a1be158cb99fb677, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<26> b_da1644efbb3f711e = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
     30, 113,  63, 187, 239,  68,  22, 218,
     38,   0,   0,   0,   4,   0,   0,   0,
    119, 182, 159, 185, 140,  21, 190, 161,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0,  98,   1,   0,   0,
     41,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     36,   0,   0,   0,   3,   0,   1,   0,
     48,   0,   0,   0,   2,   0,   1,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     65, 103, 101, 110, 116,  67, 111, 109,
    109,  97, 110, 100,  77, 115, 103,  46,
     99,  97, 112, 110, 112,  58,  65, 103,
    101, 110, 116,  67, 111, 109, 109,  97,
    110, 100,  77, 115, 103,  46, 115, 116,
     97, 114, 116,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      6,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      6,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_da1644efbb3f711e = b_da1644efbb3f711e.words;
#if !CAPNP_LITE
const ::capnp::_::RawSchema s_da1644efbb3f711e = {
  0xda1644efbb3f711e, b_da1644efbb3f711e.words, 26, nullptr, nullptr,
  0, 0, nullptr, nullptr, nullptr, { &s_da1644efbb3f711e, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<26> b_c71410885ec9a782 = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
    130, 167, 201,  94, 136,  16,  20, 199,
     38,   0,   0,   0,   4,   0,   0,   0,
    119, 182, 159, 185, 140,  21, 190, 161,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0,  90,   1,   0,   0,
     41,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     36,   0,   0,   0,   3,   0,   1,   0,
     48,   0,   0,   0,   2,   0,   1,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     65, 103, 101, 110, 116,  67, 111, 109,
    109,  97, 110, 100,  77, 115, 103,  46,
     99,  97, 112, 110, 112,  58,  65, 103,
    101, 110, 116,  67, 111, 109, 109,  97,
    110, 100,  77, 115, 103,  46, 115, 116,
    111, 112,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      6,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      6,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_c71410885ec9a782 = b_c71410885ec9a782.words;
#if !CAPNP_LITE
const ::capnp::_::RawSchema s_c71410885ec9a782 = {
  0xc71410885ec9a782, b_c71410885ec9a782.words, 26, nullptr, nullptr,
  0, 0, nullptr, nullptr, nullptr, { &s_c71410885ec9a782, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
}  // namespace schemas
}  // namespace capnp

// =======================================================================================

namespace control {

// AgentCommandMsg
constexpr uint16_t AgentCommandMsg::_capnpPrivate::dataWordSize;
constexpr uint16_t AgentCommandMsg::_capnpPrivate::pointerCount;
#if !CAPNP_LITE
constexpr ::capnp::Kind AgentCommandMsg::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* AgentCommandMsg::_capnpPrivate::schema;
#endif  // !CAPNP_LITE

#ifndef _MSC_VER
constexpr  ::uint8_t AgentCommandMsg::START;
#endif
#ifndef _MSC_VER
constexpr  ::uint8_t AgentCommandMsg::STOP;
#endif

}  // namespace

