#include "Behaviours/constraints/Answer1581966891046Constraints.h"
/*PROTECTED REGION ID(ch1581966891046) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{

// Behaviour:Answer
}
