#include "Behaviours/constraints/Close1568801712239Constraints.h"
/*PROTECTED REGION ID(ch1568801712239) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{

// Behaviour:Close
}
