#include "Behaviours/constraints/Goleft1568801601566Constraints.h"
/*PROTECTED REGION ID(ch1568801601566) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {

// Behaviour:Goleft
}
