#include "Behaviours/constraints/Goright1568801619244Constraints.h"
/*PROTECTED REGION ID(ch1568801619244) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {

// Behaviour:Goright
}
