#include "Behaviours/constraints/Goup1568801639189Constraints.h"
/*PROTECTED REGION ID(ch1568801639189) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {

// Behaviour:Goup
}
