#include "Behaviours/constraints/Move1568825137528Constraints.h"
/*PROTECTED REGION ID(ch1568825137528) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{

    //Behaviour:Move
     
}
