#include "Behaviours/constraints/Open1568801700485Constraints.h"
/*PROTECTED REGION ID(ch1568801700485) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{

// Behaviour:Open
}
