#include "Behaviours/constraints/Pickup1568801673599Constraints.h"
/*PROTECTED REGION ID(ch1568801673599) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {

// Behaviour:Pickup
}
