#include "Behaviours/constraints/Stop1555602210283Constraints.h"
/*PROTECTED REGION ID(ch1555602210283) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {

// Behaviour:Stop
}
