#include "Behaviours/constraints/Test1559635479527Constraints.h"
/*PROTECTED REGION ID(ch1559635479527) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {

// Behaviour:Test
}
