#include "constraints/Human1575291300084Constraints.h"
/*PROTECTED REGION ID(ch1575291300084) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:Human
/*
 * Tasks:
 * - EP:1575291327598 : Human (1575291322015)
 *
 * States:
 * - SendTasksScripted (1575291336838)
 *
 * Vars:
 */

// State: SendTasksScripted
} // namespace alicaAutogenerated
