#include "constraints/Operate1575655614484Constraints.h"
/*PROTECTED REGION ID(ch1575655614484) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:Operate
/*
 * Tasks:
 * - EP:1575655644510 : Serve (1555601344076)
 * - EP:1575655650043 : GenerateTasks (1575291322015)
 *
 * States:
 * - Serve (1575655659597)
 * - SimHuman (1575655660934)
 *
 * Vars:
 */

// State: Serve
// State: SimHuman
} // namespace alicaAutogenerated
