#include "constraints/Serve1568825275605Constraints.h"
/*PROTECTED REGION ID(ch1568825275605) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:Serve
/*
 * Tasks:
 * - EP:1568825285315 : Serve (1555601344076)
 *
 * States:
 * - WaitForTask (1568825288640)
 * - MoveToPosition (1568825309813)
 * - ManipulateObject (1571661663929)
 * - TransportToPosition (1573418710533)
 * - AnswerQuestion (1581966845202)
 *
 * Vars:
 */

// State: WaitForTask
// State: MoveToPosition
// State: ManipulateObject
// State: TransportToPosition
// State: AnswerQuestion
} // namespace alicaAutogenerated
