#include "constraints/Transport1573418869596Constraints.h"
/*PROTECTED REGION ID(ch1573418869596) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:Transport
/*
 * Tasks:
 * - EP:1573418933317 : 1555601323994 (1555601323994)
 *
 * States:
 * - Search (1573418936395)
 * - PickUp (1573418937725)
 * - MoveDestination (1573418938883)
 * - PutDown (1573418939737)
 * - MoveClose (1573418941076)
 * - TransportDone (1573418943460)
 *
 * Vars:
 */

// State: Search
// State: PickUp
// State: MoveDestination
// State: PutDown
// State: MoveClose
// State: TransportDone
} // namespace alicaAutogenerated
