#include "Behaviours/Answer1581966891046.h"
#include <memory>

/*PROTECTED REGION ID(inccppBC1581966891046) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Behaviour:Answer
// Check of RuntimeCondition - (Name): 1581966891049, (ConditionString): , (Comment) :

/*
 * Available Vars:
 */
bool RunTimeCondition1581966891049::evaluate(std::shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1581966891049) ENABLED START*/
    std::cout << "The RuntimeCondition 1581966891049 in Behaviour Answer is not implement yet!" << std::endl;
    return false;
    /*PROTECTED REGION END*/
}
// Check of PreCondition - (Name): 1581966891048, (ConditionString):  , (Comment) :

/*
 * Available Vars:
 */
bool PreCondition1581966891048::evaluate(std::shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1581966891048) ENABLED START*/
    std::cout << "The PreCondition 1581966891048 in Behaviour Answer is not implement yet!" << std::endl;
    return false;
    /*PROTECTED REGION END*/
}
// Check of PostCondition - (Name): 1581966891050, (ConditionString):  , (Comment) :

/*
 * Available Vars:
 */
bool PostCondition1581966891050::evaluate(std::shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1581966891050) ENABLED START*/
    std::cout << "The PostCondition 1581966891050 in Behaviour Answer is not implement yet!" << std::endl;
    return false;
    /*PROTECTED REGION END*/
}

} // namespace alicaAutogenerated
