#include "Behaviours/Close1568801712239.h"
#include <memory>

/*PROTECTED REGION ID(inccppBC1568801712239) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {
// Behaviour:Close

} // namespace alicaAutogenerated
