#include "Behaviours/Godown1568801657637.h"
#include <memory>

/*PROTECTED REGION ID(inccppBC1568801657637) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {
// Behaviour:Godown

} // namespace alicaAutogenerated
