#include "Behaviours/Goleft1568801601566.h"
#include <memory>

/*PROTECTED REGION ID(inccppBC1568801601566) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {
// Behaviour:Goleft

} // namespace alicaAutogenerated
