#include "Behaviours/Goright1568801619244.h"
#include <memory>

/*PROTECTED REGION ID(inccppBC1568801619244) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {
// Behaviour:Goright

} // namespace alicaAutogenerated
