#include "Behaviours/Goup1568801639189.h"
#include <memory>

/*PROTECTED REGION ID(inccppBC1568801639189) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {
// Behaviour:Goup

} // namespace alicaAutogenerated
