#include  "Behaviours/Manipulate1571687572903.h"
#include <memory>

/*PROTECTED REGION ID(inccppBC1571687572903) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
    //Behaviour:Manipulate

} /* namespace alica */
