#include "Behaviours/Move1568825137528.h"
#include <memory>

/*PROTECTED REGION ID(inccppBC1568825137528) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {
// Behaviour:Move

} // namespace alicaAutogenerated
