#include "Behaviours/Open1568801700485.h"
#include <memory>

/*PROTECTED REGION ID(inccppBC1568801700485) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {
// Behaviour:Open

} // namespace alicaAutogenerated
