#include "Behaviours/Pickup1568801673599.h"
#include <memory>

/*PROTECTED REGION ID(inccppBC1568801673599) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Behaviour:Pickup

} // namespace alicaAutogenerated
