#include "Behaviours/SendTasks1575291385685.h"
#include <memory>

/*PROTECTED REGION ID(inccppBC1575291385685) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Behaviour:SendTasks

} // namespace alicaAutogenerated
