#include  "Behaviours/Spawn1558533534825.h"
#include <memory>

/*PROTECTED REGION ID(inccppBC1558533534825) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
    //Behaviour:Spawn

} /* namespace alica */
