#include "Behaviours/Stop1555602210283.h"
#include <memory>

/*PROTECTED REGION ID(inccppBC1555602210283) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {
// Behaviour:Stop

} // namespace alicaAutogenerated
