#include "Behaviours/Test1559635479527.h"
#include <memory>

/*PROTECTED REGION ID(inccppBC1559635479527) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Behaviour:Test

} // namespace alicaAutogenerated
